### ISSUE TITLE
Issue: Needs & Shelters show incorrect location

### ISSUE THREAD

**Issue by thedavidhanks** [sketch-city/harvey-api#119]
The detail page for the Needs and Shelters shows the same incorrect location for all Shelters and Needs.

https://api.harveyneeds.org/needs/83303
![image](https://user-images.githubusercontent.com/13823414/30348910-9d1a6874-97d6-11e7-895e-b42d2fad33e3.png)

**Comment by jwo** [comment]
@thedavidhanks Are you entering the name of the shelter into the  "Where is it" ?

When I do, it finds it:

<img width="1371" alt="screen shot 2017-09-12 at 4 26 01 pm" src="https://user-images.githubusercontent.com/123075/30349074-33c748d2-97d7-11e7-967e-ceacd2f7b3d8.png">

**Comment by jwo** [comment]
It may be that the latitude / longitude was never entered for those needs. They just need to be edited with our super cool new mapping finder.

**Comment by thedavidhanks** [comment]
I'm going to https://api.harveyneeds.org/needs and clicking on "Show" or "Update"

**Comment by Sporky023** [comment]
Sounds like a UX issue.  When there's a place in a view for a map, if no lat/lon is present then there should instead be a message like "no location for this need".  A map showing a default location sounds like misinformation.

**Comment by brettapeters** [comment]
This might have to do with the needs form. If the Google autocomplete input doesn't send an api request before the user submits the form (they might just paste in an address and click out, or not click the suggestions dropdown at all) the form will not have lat/lng when it is submitted. To fix, we could fire off a request on blur and choose the first suggestion. Or just not try to show a map if there is no lat/lng available.

**Comment by Sporky023** [comment]
This pull disables the map if no lat/lon present.  Showing no information better than showing disinformation.

https://github.com/sketch-city/harvey-api/pull/123

**Comment by Sporky023** [comment]
I've created another pull request (**please note the feature is incomplete and potentially hazardous to use, as it is not thought through very well**).  In this second one it saves the `google_place` from the `/needs/new` form in the database record for a Need.

The idea is that when you go to `needs/:id/edit` the form will now be pre-populated with the original location string that the user entered.  This allows for re-geocoding to enter addresses and lat/lon values.

I say it's dangerous because there's a possibility of the following:

1. run migrations on production data resulting in null values for existing Need records
2. navigate to exiting Need's edit page
3. the `google_place` field is populated as null
4. **here's the part I'm unsure of**:  this possibly trigger a geocoding on a blank string, resulting in existing lat/lon or address data being overwritten by the goecoding JS as blank.
5.  click "save", which now saves blank values over existing non-blank values in the db record.

Someone more familiar with the project should review this possibility.
We tried to click-test this workflow on our development machine, but we were blocked because when we created a Need record we were faced with message like "awaiting approval" and we couldn't figure out how to approve it.

Anyway, here is that pull:  https://github.com/sketch-city/harvey-api/pull/124

**Comment by jwo** [comment]
@Sporky023 

> We tried to click-test this workflow on our development machine, but we were blocked because when we created a Need record we were faced with message like "awaiting approval" and we couldn't figure out how to approve it.

If you create a user record, and then using `rails console` you upgrade it to an admin, you can both:

1. Make edits directly without updates going to the queue
2. Update and approve queue updates that anonymous users submit

**Comment by jwo** [comment]
This should be working now. If you visit a need that did not save a lat/lon, it won't show a map

But if you do visit a need that used our address finder, and got a map (lat/lon), it will show the correct map.

Going to close for now, but if I misunderstand, please comment and reopen. Thanks yall!
